Repository VM-Chinese-translate-group/Prey, pull requests merged in 2023-12, with the labels that each got.

#9 ftbq第二章
  Patch-Pack-CN/config/ftbquests/quests/chapters/chapter_2a.snbt
Labels: ftbquest, need review

#14 翻译FTB quest剩余章节
  Patch-Pack-CN/config/ftbquests/quests/chapter_groups.snbt
  Patch-Pack-CN/config/ftbquests/quests/chapters/shop.snbt
  Patch-Pack-CN/config/ftbquests/quests/chapters/starting.snbt
Labels: ftbquest, need review

#17 每周日凌晨 00:00 执行汉化包的 Release
  .github/workflows/packer.yml
  source_files/packer.py
  source_files/packer_config.json
Labels: .github

#18 Update shop.snbt
  Patch-Pack-CN/config/ftbquests/quests/chapters/shop.snbt
Labels: ftbquest, need review

#15 Skill
  Patch-Pack-CN/config/puffish_skills/categories/Arcane_Ranger/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Arcane_Ranger/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Archery/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Archery/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Battlemage/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Battlemage/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Beastmaster/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Beastmaster/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Berserker/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Berserker/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Bloodripper/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Bloodripper/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Bounty_Hunter/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Bounty_Hunter/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Conjurer/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Conjurer/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Crafting/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Crafting/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Dreamweaver/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Dreamweaver/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Elixirs/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Explorer/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Explorer/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Guardian/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Guardian/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Kensei/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Kensei/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Magic/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Magic/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Melee/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Melee/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Mining/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Mining/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Spellsword/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Spellsword/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Spirit_Caller/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Spirit_Caller/definitions.json
  Patch-Pack-CN/config/puffish_skills/categories/Starter/category.json
  Patch-Pack-CN/config/puffish_skills/categories/Starter/definitions.json
Labels: need review

#7 kubejs/lang 汉化
  Patch-Pack-CN/kubejs/assets/kubejs/lang/zh_cn.json
Labels: need review

#6 dungeons_gear
  Patch-Pack-CN/kubejs/assets/dungeons_gear/lang/en_us.json
  Patch-Pack-CN/kubejs/assets/dungeons_gear/lang/zh_cn.json
Labels: need review

#4 Dungeons Mob
  Patch-Pack-CN/kubejs/assets/dungeons_mobs/lang/zh_cn.json
Labels: need review

#5 dungeons plus
  Patch-Pack-CN/kubejs/assets/dungeons_plus/lang/zh_cn.json
Labels: need review

#3 Deeper And Darker
  Patch-Pack-CN/kubejs/assets/deeperdarker/lang/zh_cn.json
Labels: need review

#8 Tooltip
  Patch-Pack-CN/kubejs/client_scripts/tooltips.js
Labels: need review

#28 Update shop.snbt
  Patch-Pack-CN/config/ftbquests/quests/chapters/shop.snbt
Labels: ftbquest, need review

#27 Ftbquest starting
  Patch-Pack-CN/config/ftbquests/quests/chapters/starting.snbt
Labels: ftbquest, need review

#24 Kubejs翻译
  Patch-Pack-CN/kubejs/assets/kubejs/lang/en_us.json
  Patch-Pack-CN/kubejs/assets/kubejs/lang/zh_cn.json
Labels: need review

#22 assortedtools翻译
  Patch-Pack-CN/kubejs/assets/assortedtools/lang/zh_cn.json
Labels: need review

#30 真实rpg尸体翻译
  Patch-Pack-CN/kubejs/assets/realmrpg_skeletons/lang/zh_cn.json
Labels: need review

#29 Undead revamp2翻译
  Patch-Pack-CN/kubejs/assets/undead_revamp2/lang/zh_cn.json
Labels: need review
